name = "nhangara-mirim-game"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Environment variables
[vars]
HEDERA_NETWORK = "mainnet"
ENVIRONMENT = "production"

# Preview environment
[env.preview]
pages_build_output_dir = "dist"

[env.preview.vars]
HEDERA_NETWORK = "testnet"
ENVIRONMENT = "preview"

# Production environment
[env.production]
pages_build_output_dir = "dist"

[env.production.vars]
HEDERA_NETWORK = "mainnet"
ENVIRONMENT = "production"

# Secrets são configurados via Cloudflare Dashboard ou wrangler secret put
# Os secrets ficam armazenados no Cloudflare Secrets Store
# e são acessados pelos Workers através da variável env

# Para configurar os secrets, use os comandos:
# wrangler secret put HEDERA_ACCOUNT_ID_DEV
# wrangler secret put HEDERA_PRIVATE_KEY_DEV
# wrangler secret put HEDERA_PUBLIC_KEY_DEV
# wrangler secret put HEDERA_ACCOUNT_ID_PROD
# wrangler secret put HEDERA_PRIVATE_KEY_PROD
# wrangler secret put HEDERA_PUBLIC_KEY_PROD 